import { computed, type ComputedRef } from 'vue';
import { useI18n } from 'vue-i18n';

export interface GalleryItem {
    src: string;
    caption: string;
}

type Locale = 'cs' | 'en' | 'uk';

const captions: Record<Locale, Record<string, string>> = {
    cs: {
        rekonstrukce: 'Rekonstrukce pokoje',
        pokladka: 'Pokládka dlažby',
        dlazby: 'Dlažby',
        detail: 'Dekorativní obklad',
        stuk: 'Dekorativní štuk s plátkovým zlatem',
        mural: 'Umělecký mural',
        mural_detail: 'Mural — atmosférní pohled',
        fasada: 'Rekonstrukce fasády',
        led: 'Pokoj s LED osvětlením',
        podlaha: 'Pokládka dřevěné podlahy',
        sprcha: 'Obklad sprchového koutu',
        stuk_oliva: 'Dekorativní štuk — olivový',
        stuk_modra: 'Dekorativní štuk — modrý',
        schody: 'Schodiště z velkoformátové dlažby',
        mural_autor: 'Autor u svého muralu',
        priprava: 'Příprava pokoje k rekonstrukci',
        kamen_vstup: 'Kamenný obklad ve vstupu',
        kamen_dvere: 'Kamenný obklad kolem dveří',
        barevna_stena: 'Barevná stěna a podhled',
        zelena: 'Zelená stěna',
        obklad_prubeh: 'Obklad koupelny — průběh',
        sprcha2: 'Sprchový kout — mramorový obklad',
        wc: 'Obklad WC s umyvadlem',
        zatepleni: 'Zateplení fasády',
        fasada_priprava: 'Fasáda — příprava',
        schody_nater: 'Schodiště — nátěr',
        dlazba_detail: 'Velkoformátová dlažba — detail',
        dlazba_chodba: 'Kamenná dlažba v chodbě',
        dlazba_podesta: 'Kamenná dlažba — podesta',
        vstup_dlazba: 'Vstup — pokládka dlažby',
        obklad_pokladka: 'Obklad koupelny — pokládka',
        nivelace: 'Samonivelační podlaha',
        nivelace2: 'Samonivelační stěrka',
        koupelna_detail: 'Koupelna — detail obkladu',
        wc_instalace: 'WC — instalace',
        schody_pokladka: 'Schodiště — pokládka dlažby',
    },
    en: {
        rekonstrukce: 'Room renovation',
        pokladka: 'Tile laying',
        dlazby: 'Tile samples',
        detail: 'Decorative tile',
        stuk: 'Decorative stucco with gold leaf',
        mural: 'Artistic mural',
        mural_detail: 'Mural — atmospheric view',
        fasada: 'Facade renovation',
        led: 'Room with LED lighting',
        podlaha: 'Wooden floor laying',
        sprcha: 'Shower tiling',
        stuk_oliva: 'Decorative stucco — olive',
        stuk_modra: 'Decorative stucco — blue',
        schody: 'Staircase in large-format tile',
        mural_autor: 'Artist with his mural',
        priprava: 'Room prepared for renovation',
        kamen_vstup: 'Stone cladding in the entrance',
        kamen_dvere: 'Stone cladding around the doorway',
        barevna_stena: 'Coloured wall and ceiling',
        zelena: 'Green wall',
        obklad_prubeh: 'Bathroom tiling in progress',
        sprcha2: 'Shower — marble tiling',
        wc: 'WC tiling with washbasin',
        zatepleni: 'Facade insulation',
        fasada_priprava: 'Facade — preparation',
        schody_nater: 'Staircase — painting',
        dlazba_detail: 'Large-format tile — detail',
        dlazba_chodba: 'Stone tiling in the hallway',
        dlazba_podesta: 'Stone tiling — landing',
        vstup_dlazba: 'Entrance — tile laying',
        obklad_pokladka: 'Bathroom tiling — laying',
        nivelace: 'Self-levelling floor',
        nivelace2: 'Self-levelling screed',
        koupelna_detail: 'Bathroom — tiling detail',
        wc_instalace: 'WC — installation',
        schody_pokladka: 'Staircase — tile laying',
    },
    uk: {
        rekonstrukce: 'Реконструкція кімнати',
        pokladka: 'Укладання плитки',
        dlazby: 'Зразки плитки',
        detail: 'Декоративна плитка',
        stuk: 'Декоративна штукатурка з сухозліткою',
        mural: 'Художній мурал',
        mural_detail: 'Мурал — атмосферний вид',
        fasada: 'Реконструкція фасаду',
        led: 'Кімната з LED-підсвіткою',
        podlaha: 'Укладання дерев’яної підлоги',
        sprcha: 'Облицювання душової',
        stuk_oliva: 'Декоративний штук — оливковий',
        stuk_modra: 'Декоративний штук — синій',
        schody: 'Сходи з великоформатної плитки',
        mural_autor: 'Автор біля свого муралу',
        priprava: 'Підготовка кімнати до реконструкції',
        kamen_vstup: 'Кам’яне облицювання у вході',
        kamen_dvere: 'Кам’яне облицювання навколо дверей',
        barevna_stena: 'Кольорова стіна та підвісна стеля',
        zelena: 'Зелена стіна',
        obklad_prubeh: 'Облицювання ванної — у процесі',
        sprcha2: 'Душова — мармурове облицювання',
        wc: 'Облицювання санвузла з умивальником',
        zatepleni: 'Утеплення фасаду',
        fasada_priprava: 'Фасад — підготовка',
        schody_nater: 'Сходи — фарбування',
        dlazba_detail: 'Великоформатна плитка — деталь',
        dlazba_chodba: 'Кам’яна плитка в коридорі',
        dlazba_podesta: 'Кам’яна плитка — майданчик',
        vstup_dlazba: 'Вхід — укладання плитки',
        obklad_pokladka: 'Облицювання ванної — укладання',
        nivelace: 'Самовирівнювальна підлога',
        nivelace2: 'Самовирівнювальна стяжка',
        koupelna_detail: 'Ванна — деталь облицювання',
        wc_instalace: 'Санвузол — встановлення',
        schody_pokladka: 'Сходи — укладання плитки',
    },
};

const sources: { src: string; key: string }[] = [
    { src: '/gallery/rekonstrukce-pokoje.webp', key: 'rekonstrukce' },
    { src: '/gallery/pokladka-dlazby.webp', key: 'pokladka' },
    { src: '/gallery/dlazby.webp', key: 'dlazby' },
    { src: '/gallery/projekt-04.webp', key: 'detail' },
    { src: '/gallery/dekorativni-stuk-koral.webp', key: 'stuk' },
    { src: '/gallery/mural-portret.webp', key: 'mural' },
    { src: '/gallery/mural-portret-detail.webp', key: 'mural_detail' },
    { src: '/gallery/autor-u-muralu.webp', key: 'mural_autor' },
    { src: '/gallery/dekorativni-stuk-oliva.webp', key: 'stuk_oliva' },
    { src: '/gallery/dekorativni-stuk-modra.webp', key: 'stuk_modra' },
    { src: '/gallery/obklad-sprchoveho-koutu.webp', key: 'sprcha' },
    { src: '/gallery/pokladka-drevene-podlahy.webp', key: 'podlaha' },
    { src: '/gallery/pokoj-led-osvetleni.webp', key: 'led' },
    { src: '/gallery/schodiste-kamenna-dlazba.webp', key: 'schody' },
    { src: '/gallery/rekonstrukce-fasady.webp', key: 'fasada' },
    { src: '/gallery/kamenny-obklad-vstup.webp', key: 'kamen_vstup' },
    { src: '/gallery/kamenny-obklad-dvere.webp', key: 'kamen_dvere' },
    { src: '/gallery/sprchovy-kout-mramor.webp', key: 'sprcha2' },
    { src: '/gallery/wc-obklad-umyvadlo.webp', key: 'wc' },
    { src: '/gallery/obklad-koupelny-pokladka.webp', key: 'obklad_pokladka' },
    { src: '/gallery/obklad-koupelny-prubeh.webp', key: 'obklad_prubeh' },
    { src: '/gallery/koupelna-detail-obkladu.webp', key: 'koupelna_detail' },
    { src: '/gallery/wc-instalace.webp', key: 'wc_instalace' },
    { src: '/gallery/kamenna-dlazba-detail.webp', key: 'dlazba_detail' },
    { src: '/gallery/kamenna-dlazba-chodba.webp', key: 'dlazba_chodba' },
    { src: '/gallery/kamenna-dlazba-podesta.webp', key: 'dlazba_podesta' },
    { src: '/gallery/vstup-pokladka-dlazby.webp', key: 'vstup_dlazba' },
    { src: '/gallery/schodiste-pokladka-dlazby.webp', key: 'schody_pokladka' },
    { src: '/gallery/schodiste-nater.webp', key: 'schody_nater' },
    { src: '/gallery/zatepleni-fasady.webp', key: 'zatepleni' },
    { src: '/gallery/fasada-priprava.webp', key: 'fasada_priprava' },
    { src: '/gallery/barevna-stena-podhled.webp', key: 'barevna_stena' },
    { src: '/gallery/zelena-stena.webp', key: 'zelena' },
    { src: '/gallery/samonivelacni-podlaha.webp', key: 'nivelace' },
    { src: '/gallery/samonivelacni-sterka.webp', key: 'nivelace2' },
    { src: '/gallery/priprava-pokoje.webp', key: 'priprava' },
];

export function useGallery(): { items: ComputedRef<GalleryItem[]> } {
    const { locale } = useI18n();
    const items = computed<GalleryItem[]>(() => {
        const c = captions[locale.value as Locale] || captions.cs;
        return sources.map(({ src, key }) => ({ src, caption: c[key] }));
    });
    return { items };
}
